= Nimoy

A testing and specification framework for Python 3, heavily inspired by the amazing http://spockframework.org/[Spock Framework].

image:https://badge.fury.io/py/nimoy-framework.svg["PyPI version", link="https://badge.fury.io/py/nimoy-framework"]
image:https://travis-ci.org/browncoat-ninjas/nimoy.svg?branch=master["Build Status", link="https://travis-ci.org/browncoat-ninjas/nimoy"]

== Installation

```
pip install nimoy-framework
```

== Why?

The http://spockframework.org/[Spock Framework] has set a new standard as to what testing frameworks should be like - beautiful, expressive, pragmatic and fun.

While `unittest`, https://github.com/pytest-dev/pytest[pytest] and https://github.com/nose-devs/nose2[nose2] are great, there's still room for improvement.

The aim of this project is to port Spock to Python while maintaining the original vision as much as possible.

== Features

* Based on `unittest`, so minimal dependencies are required and specifications are recognized by IDEs and report analyzers.
* Reduction of boilerplate code.
* Write detailed specifications with clear distinction.
* Auto discovery of specifications.
* Write data-driven specifications.
* Pretty mock behavior assertion.
* See fancy detailed assertion failure reports.

== Learn More

* https://browncoat-ninjas.github.io/nimoy/[About]
* https://browncoat-ninjas.github.io/nimoy/user-guide/[User Guide]
* https://browncoat-ninjas.github.io/nimoy/examples/[Examples]
* https://browncoat-ninjas.github.io/nimoy/contributing/[Contributing]

== License

Apache License 2.0

== In memory of Leonard Nimoy 1931-2015
